name: 'integrity_energy_dbt'
version: '1.0.0'
config-version: 2

profile: integrity_energy_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  integrity_energy_dbt:
    prod-dbt-base:
      +tags: [daily]
#      +schema: prod-dbt-base
    prod-dbt-intermediate:
      +tags: [daily]
#      +schema: prod-dbt-intermediate
    prod-dbt-mart:
      +tags: [daily]
#      +schema: prod-dbt-mart