name: 'integrity_energy_dbt'
version: '1.0.0'
config-version: 2

profile: integrity_energy_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  integrity_energy_dbt:
    prod-dbt-base:
      +tags: [daily]
      +materialized: 'materialized_view'
      +schema: dbt-base
    prod-dbt-intermediate:
      +tags: [daily]
      +materialized: 'view'
      +schema: dbt-intermediate
    prod-dbt-mart:
      +tags: [daily]
      +materialized: 'table'
      +schema: dbt-mart