integrity_energy_dbt:
  outputs:
    prod:
      dbname: integrity-db
      host: integrity-energy.cm7f5da54gqs.us-east-1.redshift.amazonaws.com
      password: Integrity123
      port: 5439
      schema: prod-dbt-base
      threads: 4
      type: redshift
      user: integrityadmin
  target: prod