integrity_energy_dbt:
  outputs:
    prod:
      dbname: integrity-db
      schema: prod
      host: integrity-energy-prod.cm7f5da54gqs.us-east-1.redshift.amazonaws.com
      password: {{ env_var('DBT_PASSWORD') }}
      port: 5439
      threads: 4
      type: redshift
      user: {{ env_var('DBT_USER') }}
    dev:
      dbname: integrity-db
      schema: dev
      host: integrity-energy-prod.cm7f5da54gqs.us-east-1.redshift.amazonaws.com
      password: {{ env_var('DBT_PASSWORD') }}
      port: 5439
      threads: 4
      type: redshift
      user: {{ env_var('DBT_USER') }}
  target: prod