integrity_energy_dbt:
  outputs:
    prod:
      dbname: integrity-db-prod
      schema: prod
      host: integrity-energy-redshift.cm7f5da54gqs.us-east-1.redshift.amazonaws.com
      password: Integrity123
      port: 5439
      threads: 4
      type: redshift
      user: integrityadmin
    dev:
      dbname: integrity-db-dev
      schema: dev
      host: integrity-energy-redshift.cm7f5da54gqs.us-east-1.redshift.amazonaws.com
      password: Integrity123
      port: 5439
      threads: 4
      type: redshift
      user: integrityadmin
  target: dev