version: 2

sources:
# Base Models
  - name: salesforce_lead_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: salesforce_lead_base
  - name: salesforce_contact_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: salesforce_contact_base
  - name: salesforce_opportunity_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: salesforce_opportunity_base
  - name: salesforce_meter_number_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: salesforce_meter_number_base
  - name: salesforce_account_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: salesforce_account_base
  - name: bing_ads_daily_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: bing_ads_daily_base
  - name: google_ads_daily_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: google_ads_daily_base 
  - name: hubspot_daily_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: hubspot_daily_base
  - name: facebook_daily_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: facebook_daily_base
  - name: utility_lead_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: utility_lead_base
  - name: marketing_cost_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: marketing_cost_base
  - name: zoominfo_base
    database: integrity-db
    schema: prod-dbt-base
    tables:
     - name: zoominfo_base

# Intermediate Models
  - name: utility_lead_intermediate
    database: integrity-db
    schema: prod-dbt-intermediate
    tables:
     - name: utility_lead_intermediate
  - name: lead_intermediate
    database: integrity-db
    schema: prod-dbt-intermediate
    tables:
     - name: lead_intermediate
  - name: marketing_intermediate
    database: integrity-db
    schema: prod-dbt-intermediate
    tables:
     - name: marketing_intermediate
  - name: deal_intermediate
    database: integrity-db
    schema: prod-dbt-intermediate
    tables:
     - name: deal_intermediate

# Prod Models
  - name: deal_prod
    database: integrity-db
    schema: prod-dbt-mart
    tables:
     - name: deal_prod
  - name: lead_prod
    database: integrity-db
    schema: prod-dbt-mart
    tables:
     - name: lead_prod
  - name: utility_lead_prod
    database: integrity-db
    schema: prod-dbt-mart
    tables:
     - name: utility_lead_prod
  - name: marketing_prod
    database: integrity-db
    schema: prod-dbt-mart
    tables:
     - name: marketing_prod