version: 2

sources:
  - name: bing_ads
    database: integrity-db
    schema: bing_ads
    tables:
      - name: account_performance_report_daily
      - name: accounts
      - name: ad_group_performance_report_daily
      - name: ad_groups
      - name: ad_performance_report_daily
      - name: campaign_performance_report_daily
      - name: campaigns

  - name: facebook
    database: integrity-db
    schema: facebook
    tables:
      - name: activities
      - name: ad_creatives
      - name: ads
      - name: ads_insights

  - name: google_ads
    database: integrity-db
    schema: google_ads
    tables:
      - name: ads_campaignbasicstats_7446470445

  - name: google_ads_api
    database: integrity-db
    schema: google_ads_api
    tables:
      - name: account_performance_report
      - name: click_view

  - name: google_sheets
    database: integrity-db
    schema: google_sheets
    tables:
      - name: dates
      - name: monthly_cost

  - name: hubspot
    database: integrity-db
    schema: hubspot
    tables:
      - name: campaigns
      - name: companies
      - name: contacts
      - name: contacts_form_submissions
      - name: contacts_list_memberships
      - name: contacts_merged_audit
      - name: contacts_property_history
      - name: deal_pipelines
      - name: deals
      - name: email_events
      - name: engagements

  - name: linkedin_ads
    database: integrity-db
    schema: linkedin_ads
    tables:
      - name: account_users
      - name: accounts
      - name: ad_campaign_analytics
      - name: ad_creative_analytics
      - name: campaign_groups
      - name: campaigns
      - name: creatives

  - name: salesforce
    database: integrity-db
    schema: salesforce
    tables:
      - name: account
      - name: commission__c
      - name: contact
      - name: contract
      - name: event
      - name: lead
      - name: meter_number__c
      - name: opportunity
      - name: task

  - name: utility_leads
    database: integrity-db
    schema: utility_leads
    tables:
      - name: aes
      - name: enriched
      - name: utilitylead

  - name: zoominfo
    database: integrity-db
    schema: zoominfo
    tables:
      - name: zoominfo_upload_09202024